const dresses = [
    {
      id: 1,
      name: "Floral Dress",
      img: "/dress/flora.webp",
      color: "Floral",
      trend: "Summer",
      category: "Casual Wear",
      fabric: "Cotton",
      sleeveType: "Sleeveless",
      occasion: "Casual Outing",
      fitStyle: "Flared",
      pattern: "Floral",
      description: "A beautiful floral cotton dress, perfect for casual outings.",
    },
    {
      id: 2,
      name: "Red Saree",
      img: "/dress/red-saree.webp",
      color: "Red",
      trend: "Trending",
      category: "Ethnic Wear",
      fabric: "Silk",
      sleeveType: "Short Sleeve",
      occasion: "Wedding",
      fitStyle: "Regular Fit",
      pattern: "Solid",
      description: "A gorgeous red saree for wedding and festival occasions.",
    },
    {
      id: 3,
      name: "Silk Saree",
      img: "/dress/red-saree.webp",
      color: "Red",
      trend: "Trending",
      category: "Ethnic Wear",
      fabric: "Silk",
      sleeveType: "Full Sleeve",
      occasion: "Festival",
      fitStyle: "Loose Fit",
      pattern: "Embroidered",
      description: "A premium silk saree with intricate embroidery for special occasions.",
    },
    {
      id: 4,
      name: "Casual Kurti",
      img: "/dress/red-saree.webp",
      color: "Maroon",
      trend: "Casual",
      category: "Casual Wear",
      fabric: "Cotton",
      sleeveType: "Half Sleeve",
      occasion: "Office Wear",
      fitStyle: "Slim Fit",
      pattern: "Printed",
      description: "A stylish and comfortable kurti for daily office wear.",
    },
    {
      id: 5,
      name: "Party Gown",
      img: "/dress/red-saree.webp",
      color: "Golden",
      trend: "Party",
      category: "Party Wear",
      fabric: "Satin",
      sleeveType: "Off-Shoulder",
      occasion: "Party",
      fitStyle: "Bodycon",
      pattern: "Solid",
      description: "A glamorous golden gown, perfect for evening parties.",
    },
    {
      id: 6,
      name: "Designer Anarkali",
      img: "/dress/red-saree.webp",
      color: "Blue",
      trend: "Festive",
      category: "Ethnic Wear",
      fabric: "Chiffon",
      sleeveType: "Full Sleeve",
      occasion: "Festival",
      fitStyle: "Flared",
      pattern: "Embroidered",
      description: "A beautifully designed Anarkali with heavy embroidery.",
    },
    {
      id: 7,
      name: "Cotton Kurta Set",
      img: "/dress/red-saree.webp",
      color: "Beige",
      trend: "Classic",
      category: "Casual Wear",
      fabric: "Linen",
      sleeveType: "Three-Quarter Sleeve",
      occasion: "Casual Outing",
      fitStyle: "Regular Fit",
      pattern: "Striped",
      description: "A comfortable linen kurta set with stylish striped pattern.",
    },
    {
      id: 8,
      name: "Silk Dress",
      img: "/dress/cotton-silk-girl.jpeg",
      color: "Black",
      trend: "Classic",
      category: "Party Wear",
      fabric: "Silk",
      sleeveType: "Sleeveless",
      occasion: "Party",
      fitStyle: "Bodycon",
      pattern: "Solid",
      description: "A luxurious black silk dress for high-end parties.",
    },
    {
      id: 9,
      name: "Silk Pattern Dress",
      img: "/dress/silk-pattern.webp",
      color: "Blue",
      trend: "Casual",
      category: "Casual Wear",
      fabric: "Silk",
      sleeveType: "Short Sleeve",
      occasion: "Casual Outing",
      fitStyle: "Loose Fit",
      pattern: "Patterned",
      description: "A comfortable blue silk dress with a unique pattern.",
    },
    {
      id: 10,
      name: "Summer Dress",
      img: "/dress/flora.webp",
      color: "Yellow",
      trend: "Summer",
      category: "Casual Wear",
      fabric: "Cotton",
      sleeveType: "Half Sleeve",
      occasion: "Summer Outing",
      fitStyle: "Regular Fit",
      pattern: "Printed",
      description: "A bright and breezy cotton dress perfect for summer outings.",
    },
    {
      id: 11,
      name: "Casual Green Dress",
      img: "/dress/flora.webp",
      color: "Green",
      trend: "Casual",
      category: "Casual Wear",
      fabric: "Polyester",
      sleeveType: "Cold Shoulder",
      occasion: "Casual Outing",
      fitStyle: "Oversized",
      pattern: "Solid",
      description: "A trendy oversized green dress, perfect for casual outings.",
    }
  ];

  export default dresses;
